### ISSUE TITLE
Tests for blobber

### ISSUE THREAD

**Issue by Callek** [mozilla/build-blobber#1]
@rail @MihaiTabara Is there any sort of testing (besides basic pep8/pyflakes) that we can do here? I'm not very familiar with it all, but this screams like it wants a travis/coverage check with it.

**Comment by MihaiTabara** [comment]
Beside some mozharness unit testing I cannot remember of anything else done here. No integration tests/coverage/etc. From my point of view, some travis/coverage would be nice. Though, I'll defer to @rail for a stronger opinion on this.

**Comment by rail** [comment]
I just added travis support and enabled flak8 only for now. Once we have tests we can add those.
